# Generated by Django 4.2.14 on 2024-07-28 15:33

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('format', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('correct_answer', models.TextField(blank=True)),
                ('correct_answer_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('subject', models.CharField(choices=[('math_analysis_1', '数学分析上'), ('math_analysis_2', '数学分析下'), ('linear_algebra', '线性代数'), ('physics_1', '大学物理上'), ('physics_2', '大学物理下'), ('discrete_math_1', '离散数学1'), ('discrete_math_2', '离散数学2'), ('discrete_math_3', '离散数学3'), ('probability_theory', '概率论与数理统计'), ('computer_organization', '计算机组成'), ('data_structure', '数据结构'), ('algorithm', '算法设计与分析'), ('operating_system', '操作系统'), ('database', '数据库系统'), ('computer_network', '计算机网络'), ('compiler', '编译原理'), ('others', '其他')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answer_reason', models.TextField(blank=True)),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
