# Generated by Django 4.2.14 on 2024-07-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='unique_id',
        ),
    ]
