# Generated by Django 4.2.14 on 2024-07-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedQuestionSet',
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(related_name='question_sets', to='questions.question'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_question_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
