# Generated by Django 4.2.14 on 2024-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceOption',
        ),
    ]
