# Generated by Django 4.2.14 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
