# Generated by Django 4.2.14 on 2024-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('questions', '0005_question_correct_answer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='questionset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_question_sets', to='groups.group'),
        ),
    ]
